### ISSUE TITLE
Not an Issue, I just don't know how to comment on github

### ISSUE THREAD

**Issue by MentallyFloridian** [ShockMicro/CorePerspectiveModels#1]
I am creating a pack that requires this shader to work, could I have permission to have it already in the pack so that people don't need to download extra things (obviously leaving credit and a link in the description of it), or would you rather me just leave a link to the github page in the description and make the user download both packs?

**Comment by ShockMicro** [comment]
Oof- I didn't realize you commented here. Yeah, you have permission to have it already in the pack, as long as you leave credit and such.
