### ISSUE TITLE
Not working for "items" that are blocks

### ISSUE THREAD

**Issue by Zartrix** [ShockMicro/CorePerspectiveModels#5]
Item models like the one for rose bush (and probably all the other double-tall plants) do not support transparency and cannot use the shader, sadly.
Maybe there is a way to use core shaders so the item models for these types of blocks support transparency?
_This is not the same issue as #4_ 
Edit: Managed to do it myself

**Comment by SanicFan19** [comment]
https://ewanhowell.com/resourcepacks/solid-block-transparency-support

**Comment by Zartrix** [comment]
It's not about blocks. This is also closed as I already fixed it myself.
